### ISSUE TITLE
Plugin doesn't work properly with TS config file

### ISSUE THREAD

**Issue by dmitrystas** [kalimahapps/vscode-tailwind-config-viewer#12]
Plugin doesn't work properly (shows all default props instead defined ones) when I use tailwind.config.ts, but works fine with tailwind.config.js

There is a very simple config, just for a test

```
export default {
  theme: {
    colors: {
      night: '#132137',
      navy: '#1D2A30',
      sand: '#EEECE6'
    }
  }
}
```

tailwind.config.ts
![изображение_2024-04-08_094959525](https://github.com/kalimahapps/vscode-tailwind-config-viewer/assets/17676541/f9efac40-1c47-4ca3-8fbe-9f146703bc3c)

tailwind.config.js
![изображение_2024-04-08_095215867](https://github.com/kalimahapps/vscode-tailwind-config-viewer/assets/17676541/25365fa8-8c42-4172-a772-64c169e63beb)

**Comment by dmitrystas** [comment]
it looks like we should to replace

https://github.com/kalimahapps/vscode-tailwind-config-viewer/blob/e35d2ed3133c32e4bbcf481d71d0a2da4867c96a/src/tailwind-config.ts#L6

with

`import { requireFromString, importFromString } from 'module-from-string';`

and

https://github.com/kalimahapps/vscode-tailwind-config-viewer/blob/e35d2ed3133c32e4bbcf481d71d0a2da4867c96a/src/tailwind-config.ts#L125

with something like this

`workspaceConfig = (await importFromString(transpile.outputText)).default;`

**Comment by abdul-alhasany** [comment]
Thanks for the question and the solution. This is resolved in latest version.
