### ISSUE TITLE
Cannot find module 'tailwindcss-animate' 

### ISSUE THREAD

**Issue by Madgique** [kalimahapps/vscode-tailwind-config-viewer#15]
I am using Next.js and wanted to test your extension but it says to me that  :
Cannot find module 'tailwindcss-animate' 
![image](https://github.com/user-attachments/assets/24e40f59-c26c-4233-9c35-273deca1ba0f)

**Comment by abdul-alhasany** [comment]
Problably you are loading the plugin in your tailwind config and the extension is not finding it.

Do you have a sample repo? What package manager do you use?

**Comment by Madgique** [comment]
Ok I removed the `require("tailwindcss-animate")` in the `tailwind.config.ts` and it worked but why is this uncompatible? (I am new to tailwind btw). I use pnpm

**Comment by abdul-alhasany** [comment]
It is not the plugin `tailwindcss-animate` but rather the extension itself does not handle plugins. I will see if I can find a fix for that

**Comment by abdul-alhasany** [comment]
I tested it with a fresh nextjs project using pnpm and it is working. Try to test with a fresh project and let me know. I will close this issue for now but you can reply if you have any updates
