### ISSUE TITLE
Hi, just installed the extension and got this error msg

### ISSUE THREAD

**Issue by Juanescacha** [kalimahapps/vscode-tailwind-config-viewer#2]
> require() of ES Module /home/juanescacha/Repositorios/Bank Modern UI/tailwind.config.js from /home/juanescacha/.vscode/extensions/kalimahapps.tailwind-config-viewer-0.0.2/build/tailwind-config.js not supported. Instead change the require of tailwind.config.js in /home/juanescacha/.vscode/extensions/kalimahapps.tailwind-config-viewer-0.0.2/build/tailwind-config.js to a dynamic import() which is available in all CommonJS modules.

any help would be awesome :)

**Comment by abdul-alhasany** [comment]
Probably you are using ESM import in your project. If the repo you working on is public please provide a link so I can fix the extension and test it.

**Comment by Juanescacha** [comment]
sure! https://github.com/Juanescacha/Bank-Modern-UI

**Comment by abdul-alhasany** [comment]
I fixed it. You can test it with v0.0.4. It took longer than I anticipated since electron (and in turn VSCode) does not support ESM. I tested it on your repo and it is working.

**Comment by Juanescacha** [comment]
Perfect! 💯

**Comment by abdul-alhasany** [comment]
Great. If you like the extension please rate it on VSCode marketplace.
