### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by Eleksar387** [kalimahapps/vscode-tailwind-config-viewer#3]
Although I have a tailwind.config.js in my project, Tailwind config viewer is just empty. I also do not get any error message. Is it because I am having the code in Windows WSL?

**Comment by jorgepedraza88** [comment]
Me too, any updates?

**Comment by SimplySayHi** [comment]
same on MacOS 13.2.1 and latest version of VSC

**Comment by abdul-alhasany** [comment]
It was a build error. It should be fixed now. Please update to version 0.0.3.

**Comment by Eleksar387** [comment]
Thanks a lot! It works again for me.

**Comment by abdul-alhasany** [comment]
Great. Please rate the extension on marketplace if you liked it.
