### ISSUE TITLE
tailwind.config.js isn't getting read by extension

### ISSUE THREAD

**Issue by brady-sewall** [kalimahapps/vscode-tailwind-config-viewer#5]
This extension looks very useful! Our tailwind.config.js is the root directory of our repo, but unfortunately isn't getting pulled in by this extension. Is our tailwind config configured unconventionally?
[tailwind.config.js.txt](https://github.com/kalimahapps/vscode-tailwind-config-viewer/files/11194647/tailwind.config.js.txt)

**Comment by abdul-alhasany** [comment]
Do you get an error? A message to say it can not be read/found? Can you provide a link to the repo?

**Comment by abdul-alhasany** [comment]
I ran the file you attached on a local repo and it is working as expected:
![image](https://user-images.githubusercontent.com/1753883/231018041-3e369534-e0d7-4b46-a066-056a87d9f133.png)

**Comment by brady-sewall** [comment]
Thanks for looking into this. Unfortunately the repo is private, so I can't link to it. But here are a few screenshots from VS Code. BTW - I'm on a Mac (unsure if that makes a difference). 
<img width="442" alt="Screenshot 2023-04-10 at 4 44 35 PM" src="https://user-images.githubusercontent.com/38672484/231020168-c29e248a-5da5-4500-b3f7-458ded117812.png">
<img width="414" alt="Screenshot 2023-04-10 at 4 44 44 PM" src="https://user-images.githubusercontent.com/38672484/231020176-eaa14c63-9a1f-4dba-bc3b-a30e5d3edef9.png">
<img width="437" alt="Screenshot 2023-04-10 at 4 44 55 PM" src="https://user-images.githubusercontent.com/38672484/231020178-2b68c5ce-b0df-4bf3-9145-e668ba6f2d70.png">

**Comment by abdul-alhasany** [comment]
I have not tested it on a mac. 

Can you try to open developer tools `Help -> Toggle Developer Tools` and then click on the extension icon in sidebar. Check if there any errors related to the extension in developer tools and let me know.

**Comment by brady-sewall** [comment]
@abdul-alhasany here you go...
![Screenshot 2023-04-10 at 5 27 14 PM](https://user-images.githubusercontent.com/38672484/231024585-619c79fd-5e4a-4589-b2cc-b0297d1d8a2b.png)

**Comment by abdul-alhasany** [comment]
Thanks. I will try to debug it.

What version of tailwind are you using?

**Comment by brady-sewall** [comment]
Tailwind v2.2.16

**Comment by abdul-alhasany** [comment]
I think this is the issue. Try to upgrade to 3.0.0 (or preferably the latest) and check.

**Comment by brady-sewall** [comment]
I won't be able to do that right away, but will spin up a sandbox later this week to explore upgrading to see if it solves the issue.

**Comment by gaurangrshah** [comment]
Same issue for tailwind.config.ts -- seems we're not even looking for .ts files? 

![image](https://user-images.githubusercontent.com/1086269/235751733-2d16dcc7-be5a-4f51-895d-450ea5e47009.png)

**Comment by abdul-alhasany** [comment]
@gaurangrshah Yours is a different issue. Yes, .ts is not looked for. If you have a sample repo I can try to implement it for .ts config.

**Comment by KnifeFed** [comment]
@abdul-alhasany It would be great with support for `tailwind.config.ts`. Here's an example repo I found just now https://github.com/FinnDore/tailwind-ts-config-prettier

**Comment by abdul-alhasany** [comment]
@KnifeFed This should be fixed in 0.0.81. Please check and let me know.
